project_id = "admbbsdtxaebeyccjtmi"

[functions.push-vapid-key]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = false

[functions.push-unsubscribe]
verify_jwt = false

[functions.push-send]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false